# Generated by Django 5.1 on 2024-09-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experience_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date']},
        ),
    ]
