# Generated by Django 5.1 on 2025-12-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='featured',
        ),
    ]
