# Generated by Django 5.1 on 2025-12-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_experience_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='proj_type',
        ),
    ]
