# Generated by Django 5.1 on 2025-12-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_profile_profile_img_alter_profile_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
    ]
