# Generated by Django 5.1 on 2025-12-14 21:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
