# Generated by Django 5.1 on 2025-12-18 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=240), blank=True, default=list, size=4),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
