# Generated by Django 5.1 on 2025-12-18 10:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_service_description_remove_service_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_library',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='icon_name',
            field=models.CharField(default='Testing', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='icon_library',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=240), size=4),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon_name',
            field=models.CharField(default='testing', max_length=50),
            preserve_default=False,
        ),
    ]
