# Generated by Django 5.1 on 2025-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_service_icon_library_service_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_colour',
            field=models.CharField(default='green-600', max_length=120),
            preserve_default=False,
        ),
    ]
