# Generated by Django 5.1 on 2025-12-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_service_icon_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon_colour',
            field=models.CharField(default='green-600', max_length=120),
            preserve_default=False,
        ),
    ]
