# Generated by Django 5.1 on 2025-12-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_technology_icon_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
    ]
