# Generated by Django 5.1 on 2025-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_experience_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Port Harcourt', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(default='https://github.com/devRaphael13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(default='https://www.linkedin.com/in/raphaelezeigwe/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Rivers State', max_length=20),
            preserve_default=False,
        ),
    ]
